name: pind_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  figma_squircle: ^0.5.3
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  go_router: ^13.2.2
  image_picker: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
